# Generated by Django 5.1.4 on 2026-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="automationexecution",
            new_name="automation__organiz_82d9ce_idx",
            old_name="automation__organiz_82389b_idx",
        ),
        migrations.RenameIndex(
            model_name="automationexecution",
            new_name="automation__status_e30eb8_idx",
            old_name="automation__status_7e3d58_idx",
        ),
        migrations.RenameIndex(
            model_name="automationrule",
            new_name="automation__organiz_d793f5_idx",
            old_name="automation__organiz_63f42d_idx",
        ),
        migrations.RenameIndex(
            model_name="domainevent",
            new_name="domain_even_organiz_b0110a_idx",
            old_name="domain_even_organiz_57c8c2_idx",
        ),
        migrations.RenameIndex(
            model_name="domainevent",
            new_name="domain_even_organiz_b5edb3_idx",
            old_name="domain_even_organiz_050634_idx",
        ),
    ]
