# Generated by Django 5.1.4 on 2026-03-12 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_branch_manager"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customfieldvalue",
            new_name="custom_fiel_entity__e41ad1_idx",
            old_name="custom_fiel_entity__778f37_idx",
        ),
        migrations.AlterField(
            model_name="organization",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1_5", "1–5"),
                    ("6_20", "6–20"),
                    ("21_100", "21–100"),
                    ("100plus", "100+"),
                ],
                default="1_5",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(
                choices=[
                    ("retail", "Розница"),
                    ("services", "Услуги"),
                    ("sales", "Продажи"),
                    ("production", "Производство"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="mode",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("advanced", "Advanced"),
                    ("industrial", "Industrial"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationcapability",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
