# Generated by Django 5.1.4 on 2026-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spreadsheets", "0003_alter_spreadsheetsheet_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spreadsheetbinding",
            name="conflict_state",
            field=models.CharField(db_index=True, default="clean", max_length=32),
        ),
        migrations.AddField(
            model_name="spreadsheetbinding",
            name="crm_record_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="spreadsheetbinding",
            name="last_sync_direction",
            field=models.CharField(default="spreadsheet_to_crm", max_length=32),
        ),
        migrations.AddField(
            model_name="spreadsheetbinding",
            name="spreadsheet_row_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="analysis_confidence",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="last_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="preview_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="source_checksum",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="sync_policy",
            field=models.CharField(default="manual_review", max_length=32),
        ),
        migrations.AddField(
            model_name="spreadsheetmapping",
            name="confidence",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="spreadsheetmapping",
            name="is_user_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="spreadsheetmapping",
            name="sample_values",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="spreadsheetmapping",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="spreadsheetsyncjob",
            name="conflict_policy",
            field=models.CharField(default="manual_review", max_length=32),
        ),
        migrations.AddField(
            model_name="spreadsheetsyncjob",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="spreadsheetsyncjob",
            name="preview_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="spreadsheetsyncjob",
            name="totals",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
