# Generated by Django 5.1.4 on 2026-03-12 17:15

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_followup_fields"),
        (
            "organizations",
            "0007_rename_custom_fiel_entity__778f37_idx_custom_fiel_entity__e41ad1_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_organiz_7f9b0d_idx",
            old_name="cust_org_status_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_organiz_c59b00_idx",
            old_name="customers_org_created_desc_idx",
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="response_state",
            field=models.CharField(
                blank=True,
                help_text="waiting_reply | replied | no_response | not_contacted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("active", "Активный"),
                    ("inactive", "Неактивный"),
                    ("archived", "Архив"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "owner"], name="customers_organiz_fe3ada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "deleted_at"],
                name="customers_organiz_5a8588_idx",
            ),
        ),
    ]
