# Generated by Django 5.1.4 on 2026-03-12 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_organiz_f11f69_idx",
            old_name="tasks_org_assignee_status_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_organiz_aff5fb_idx",
            old_name="tasks_org_due_idx",
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
