# Generated by Django 5.1.4 on 2026-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_idempotency_keys"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="core_idempo_user_id_aa987a_idx",
            old_name="core_idempo_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="core_idempo_expires_6bf43d_idx",
            old_name="core_idempo_expires_idx",
        ),
    ]
