# Generated by Django 5.1.4 on 2026-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_organiz_86ff70_idx",
            old_name="audit_logs_organiz_8ce347_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_organiz_3308b3_idx",
            old_name="audit_logs_organiz_2fd4f9_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_organiz_6eaae7_idx",
            old_name="audit_logs_organiz_9ac432_idx",
        ),
    ]
