import logging

from celery import shared_task

logger = logging.getLogger(__name__)


@shared_task(queue="default")
def reindex_customer(customer_id: str) -> None:
    """No-op task: search_vector is generated by database."""
    logger.debug(
        'reindex_customer called for %s (search_vector is GENERATED, no action needed)',
        customer_id,
    )
