# Generated by Django 5.1.4 on 2026-03-12 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_deal_core_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deal",
            new_name="deals_organiz_9dbb54_idx",
            old_name="deals_org_pipe_stage_idx",
        ),
        migrations.RenameIndex(
            model_name="deal",
            new_name="deals_organiz_c4d727_idx",
            old_name="deals_org_status_idx",
        ),
        migrations.AlterField(
            model_name="deal",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="probability",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="0-100%", null=True
            ),
        ),
    ]
