# Generated by Django 5.1.4 on 2026-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_endpoin_f80bf6_idx",
            old_name="webhook_deli_endpoin_5ec143_idx",
        ),
    ]
