# Generated by Django 5.1.4 on 2026-03-12 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_message_template"),
        (
            "customers",
            "0008_rename_cust_org_status_idx_customers_organiz_7f9b0d_idx_and_more",
        ),
        (
            "deals",
            "0005_rename_deals_org_pipe_stage_idx_deals_organiz_9dbb54_idx_and_more",
        ),
        (
            "organizations",
            "0007_rename_custom_fiel_entity__778f37_idx_custom_fiel_entity__e41ad1_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
            ],
            options={
                "db_table": "notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities_organiz_51d970_idx",
            old_name="act_org_cust_created_idx",
        ),
        migrations.RenameIndex(
            model_name="activity",
            new_name="activities_organiz_a2b7f8_idx",
            old_name="act_org_deal_created_idx",
        ),
        migrations.RenameIndex(
            model_name="messagetemplate",
            new_name="message_tem_organiz_828cfc_idx",
            old_name="msgtpl_org_channel_idx",
        ),
        migrations.RenameIndex(
            model_name="messagetemplate",
            new_name="message_tem_organiz_3a66db_idx",
            old_name="msgtpl_shortcut_idx",
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_notes",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="deals.deal",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["organization", "customer", "-created_at"],
                name="notes_organiz_a03e3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["organization", "deal", "-created_at"],
                name="notes_organiz_059ac6_idx",
            ),
        ),
    ]
