# Generated by Django 5.1.4 on 2026-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_dde14f_idx",
            old_name="notificatio_recipie_6c406f_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_organiz_9ef220_idx",
            old_name="notificatio_organiz_378f7a_idx",
        ),
    ]
