import { createBrowserRouter, Navigate, RouterProvider } from 'react-router-dom';
import { lazy, Suspense, type ComponentType } from 'react';
import { AppShell } from '../layout/AppShell';
import { AuthShell } from '../layout/AuthShell';
import { PageLoader } from '../../shared/ui/PageLoader';
const wrap = (imp: () => Promise<{ default: ComponentType }>) => { const Comp = lazy(imp); return <Suspense fallback={<PageLoader />}><Comp /></Suspense>; };
const LoginPage = () => wrap(() => import('../../pages/auth/login'));
const RegisterPage = () => wrap(() => import('../../pages/auth/register'));
const OnboardingPage = () => wrap(() => import('../../pages/onboarding'));
const DashboardPage = () => wrap(() => import('../../pages/dashboard'));
const CustomersPage = () => wrap(() => import('../../pages/customers'));
const CustomerProfile = () => wrap(() => import('../../pages/customers/profile'));
const DealsPage = () => wrap(() => import('../../pages/deals'));
const DealProfile = () => wrap(() => import('../../pages/deals/profile'));
const TasksPage = () => wrap(() => import('../../pages/tasks'));
const ReportsPage = () => wrap(() => import('../../pages/reports'));
const AutomationsPage = () => wrap(() => import('../../pages/automations'));
const ImportsPage = () => wrap(() => import('../../pages/imports'));
const SettingsPage = () => wrap(() => import('../../pages/settings'));
const AuditPage = () => wrap(() => import('../../pages/audit'));
const router = createBrowserRouter([{ path: '/auth', element: <AuthShell />, children: [{ path: 'login', element: <LoginPage /> }, { path: 'register', element: <RegisterPage /> }] }, { path: '/onboarding', element: <OnboardingPage /> }, { path: '/', element: <AppShell />, children: [{ index: true, element: <DashboardPage /> }, { path: 'customers', element: <CustomersPage /> }, { path: 'customers/:id', element: <CustomerProfile /> }, { path: 'deals', element: <DealsPage /> }, { path: 'deals/:id', element: <DealProfile /> }, { path: 'tasks', element: <TasksPage /> }, { path: 'reports', element: <ReportsPage /> }, { path: 'automations', element: <AutomationsPage /> }, { path: 'imports', element: <ImportsPage /> }, { path: 'audit', element: <AuditPage /> }, { path: 'settings', element: <SettingsPage /> }, { path: 'settings/:section', element: <SettingsPage /> }] }, { path: '*', element: <Navigate to="/" replace /> }]);
export function AppRouter() { return <RouterProvider router={router} />; }
